language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    - secure: "bmjUMvuD9qjQG/Q/wdnBJd2RoRCfZfSUD4Jip0hK0RZYoUIUHtePjT6L5sP1sScg7i86bZc3Ja5BJG/cv74PQCczeaWq1qsJLj6yKRdHYU1TJlUy7uqcK71K0PC7gWQUu7CGXVsrK0waPohwTCUfOvPeHBR9TF0lhf3zr9jvhLg="

addons:
  coverity_scan:
    project:
      name: "wc-duck/datalibrary"
      description: "Build submitted via Travis CI"
    notification_email: fredrik.kihlander@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

See a sample project using Travis CI to run Coverity Scan build:

GitHub repository
    https://github.com/daksheshvyas/MyHelloWorld/
Travis Build
    https://travis-ci.org/daksheshvyas/MyHelloWorld

More on using Travis CI

Trouble with Travis CI?

Run your build locally, and migrate to Travis CI once things are running smoothly.




before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev-i386 g++-multilib

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..

script:
  - bam/bam compiler=$CC platform=linux_x86 config=debug -r sc test
  - bam/bam compiler=$CC platform=linux_x86 config=release -r sc test
  - bam/bam compiler=$CC platform=linux_x86_64 config=debug -r sc test
  - bam/bam compiler=$CC platform=linux_x86_64 config=release -r sc test

addons:
  coverity_scan:
    project:
      name: "wc-duck/datalibrary"
      description: "Build submitted via Travis CI"
    notification_email: fredrik.kihlander@gmail.com
    build_command_prepend: "bam/bam compiler=$CC platform=linux_x86_64 config=debug -r sc -c"
    build_command:   "bam/bam compiler=$CC platform=linux_x86_64 config=debug -r sc"
    branch_pattern: coverity_scan

