platform:
  - x86

environment:
  matrix:
    - MSVS: msvs10
      PLATFORM: win32
      CONFIG: debug
    - MSVS: msvs10
      PLATFORM: win32
      CONFIG: release
    - MSVS: msvs10
      PLATFORM: winx64
      CONFIG: debug
    - MSVS: msvs10
      PLATFORM: winx64
      CONFIG: release

install:
  - if[%PLATFORM%]==[win32] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if[%PLATFORM%]==[winx64] call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if[%PLATFORM%]==[winx64] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - start /b /i /wait script\bootstrap.bat
  - set WindowsSdkDir=C:\Program Files\Microsoft SDKs\Windows\v7.1
  - local\bam\bam.exe platform=%PLATFORM% config=%CONFIG% compiler=%MSVS% -r s
  - local\bam\bam.exe platform=%PLATFORM% config=%CONFIG% compiler=%MSVS% -r s test

build: OFF
